apiVersion: v1
kind: Service
metadata:
  name: bpmn-frontend
  labels:
    app: bpmn-frontend
    group: web
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80  
    protocol: TCP
  selector:
    app: bpmn-frontend
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: bpmn-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpmn-frontend
  template:
    metadata:
      labels:
        app: bpmn-frontend
        group: web
        tier: frontend
    spec:
      containers:
      - name: bpmn-frontend
        image: misegr/bpmn-frontend
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 80
          name: bpmn-frontend
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bpmn-frontend
  labels:
    app: bpmn-frontend
    tier: frontend  
spec:
  rules:
  - http:
      paths:
      - path: /frontend
        backend:
          serviceName: bpmn-frontend
          servicePort: 80